demo-store/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')
        ->middleware('verified');

Route::post('/home', 'HomeController@index')->name('dashboard')
        ->middleware('verified');

Route::resource('items', 'ItemController')
        ->middleware('verified');

Route::fallback('HomeController@fallback');

demo-store/app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $connection = 'mysql',  $table = 'items',  $primaryKey = 'id';
    protected $fillable = array(
        'name',
        'type',
        'quantity',
        'description',
    );

    public $timestamps = true;
}

demo-store/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

demo-store/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

demo-store/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }

    public function fallback(){
        abort(404);
    }
}

demo-store/app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use Illuminate\Http\Request;

function quickStore($item, Request $request)
{            
    $item->name         = title_case($request->name);
    $item->type         = strtoupper($request->type);
    $item->quantity     = $request->quantity;
    $item->description  = title_case($request->description);
    $item->save();
    $request->flush();
}

class ItemController extends Controller
{
    public function index()
    {
        $item = Item::cursor();
        return view('items.index', ['item' => $item]);
    }

    public function create()
    {
        return view('items.create');
    }

    public function store(Request $request)
    {
        $item = new Item;
        quickStore($item, $request);
        return redirect()->route('items.show', $item->id)
        ->with('successCreate', 'Item has been created.');

    }

    public function show($id)
    {
        $item = Item::where('id', $id)->get();
        return view('items.show', ['item' => $item]);
    }

    public function edit($id)
    {
        $item = Item::find($id);
        return view('items.edit', ['item' => $item]);
    }

    public function update(Request $request, $id)
    {
        $item = Item::find($id);
        quickStore($item, $request);
        return redirect()->route('items.show', $item->id)
        ->with('successUpdate', 'Item has been updated.');

    }

    public function destroy($id)
    {
        $item = Item::find($id)->delete();
        return redirect()->route('items.index')
        ->with('successDestroy', 'Item has been deleted.');
    }
}

demo-store/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Welcome to your Dashboard. You're logged in!</div>

                @if (session('status'))
                <div class="card-body">
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                </div>
                @endif
            </div>
        </div>
    </div>
    <br><br>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Item Tools</div>

                <div class="card-body">

                    <a href="{{ route('items.index') }}">View All Items</a> <br>
                    <a href="items/create">Create New Item</a>
                </div>
            </div>
        </div>
    </div>

    <br><br>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Users Tools: <i>Awaiting Deployment</i></div>

                <div class="card-body">

                    <a href="/users/view">View All Users</a> <br>
                    <a href="/users/create">Create New User</a>
                </div>
            </div>
        </div>
    </div>

    <br><br>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Maintenance Mode: <i>Awaiting Deployment</i></div>

                <div class="card-body">

                    <a href="/maint-on">Turn On </a> <br>
                    <a href="/maint-off">Turn Off </a>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection

demo-store/resources/views/items/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ title_case('you can create new items here to display. all
                    fields are required.') }}</div>

                @if (session('status'))
                <div class="card-body">
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                </div>
                @endif
            </div>
        </div>
    </div>

    <br>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Items Properties') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('items.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" placeholder="e.g. Mission Impossible 4: Fallout"
                                    name="name" value="" required autofocus aria-describedby="nameHelpBlock">
                                <small id="nameHelpBlock" class="form-text text-muted">
                                    Letters, numbers and spaces only. No special characters.
                                </small>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="type" class="col-md-4 col-form-label text-md-right">{{ __('Type') }}</label>

                            <div class="col-md-6">
                                <input id="type" type="text" class="form-control" placeholder="e.g. DVD, Novel, Textbook, USB"
                                    name="type" value="" required aria-describedby="typeHelpBlock">
                                <small id="typeHelpBlock" class="form-text text-muted">
                                    Letters, numbers and spaces only. No special characters.
                                </small>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="quantity" class="col-md-4 col-form-label text-md-right">{{ __('Quantity') }}</label>

                            <div class="col-md-6">
                                <input id="quantity" type="number" class="form-control" title="Enter digits only"
                                    placeholder="How many of this item are in stock?" name="quantity" required
                                    aria-describedby="quantityHelpBlock">
                                <small id="quantityHelpBlock" class="form-text text-muted">
                                    Positive numbers only. No spaces, special characters.
                                </small>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description')
                                }}</label>

                            <div class="col-md-6">
                                <textarea name="description" id="description" rows="6" class="form-control" placeholder="Add a production description here"
                                    required aria-describedby="descriptionHelpBlock"></textarea>
                                <small id="descriptionHelpBlock" class="form-text text-muted">
                                    Letters, numbers and spaces only. No special characters.
                                </small>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary btn-block .sr-only">
                                    {{ __('Create New Item') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

demo-store/resources/views/items/delete.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ title_case('you can delete existing items here') }}</div>

                    @if (session('status'))
                        <div class="card-body">
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        </div>
                    @endif
            </div>
        </div>
    </div>

    <br>

    <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Item Removal') }}</div>
    
                    <div class="card-body">
                        <form method="POST" action="{{ route('destroyItem') }}">
                            @csrf

                            <div class="form-group row">
                                    <label for="id" class="col-md-4 col-form-label text-md-right">{{ __('I Want To Delete') }}</label>
        
                                    <div class="col-md-6">
                                        <select name="id" class="form-control" id="id" autofocus required>
                                            <option value="" disabled selected>Choose Item</option>
                                            @foreach ($items as $item)
                                            <option value="{{ $item['id'] }}"> {{ $item['name'] . ' : ' . $item['type'] }} </option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <br>
    
                            
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Delete') }}   
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
</div>

@endsection

demo-store/resources/views/items/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ title_case('you can update existing items here. All fields are required,
                    but can be left as-is.') }}</div>

                @if (session('status'))
                <div class="card-body">
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                </div>
                @endif
            </div>
        </div>
    </div>

    <br>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Item Property Edit') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('items.update', $item->id) }}">
                        @method('PUT')
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('New Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" required value="{{ $item->name }}"
                                    autofocus aria-describedby="nameHelpBlock">
                                <small id="nameHelpBlock" class="form-text text-muted">
                                    Letters, numbers and spaces only. No special characters.
                                </small>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="type" class="col-md-4 col-form-label text-md-right">{{ __('New Type') }}</label>

                            <div class="col-md-6">
                                <input id="type" type="text" class="form-control" name="type" required value="{{ $item->type }}"
                                    aria-describedby="typeHelpBlock">
                                <small id="typeHelpBlock" class="form-text text-muted">
                                    Letters, numbers and spaces only. No special characters.
                                </small>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="quantity" class="col-md-4 col-form-label text-md-right">{{ __('New Quantity')
                                }}</label>

                            <div class="col-md-6">
                                <input id="quantity" type="number" class="form-control" required value="{{ $item->quantity }}"
                                    name="quantity" aria-describedby="quantityHelpBlock">
                                <small id="quantityHelpBlock" class="form-text text-muted">
                                    Positive numbers only. No spaces, special characters.
                                </small>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('New
                                Description') }}</label>

                            <div class="col-md-6">
                                <textarea name="description" id="description" rows="6" required class="form-control"
                                    aria-describedby="descriptionHelpBlock">{{ $item->description }}</textarea>
                                <small id="descriptionHelpBlock" class="form-text text-muted">
                                    Letters, numbers and spaces only. No special characters.
                                </small>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary btn-block">
                                    {{ __('Update This Item') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

demo-store/resources/views/items/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    
    @if(session('successDestroy'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-danger">
                    {{ session('successDestroy') }}
                </div>
            </div>
        </div>
    @else
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">You will find a list of all items in the store here. Have fun!</div>
    
                    @if (session('status'))
                    <div class="card-body">
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    </div>
                    @endif
                </div>
            </div>
        </div> <br>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Item(s) List: </div>

                <div class="card-body">

                    @if(!filled($item))
                    <p>
                        {!! __('You are out of stock on all items.<br> Now is a good time to restock.') !!}
                    </p>
                    <p>
                        <a href="{{ route('createItem') }}">Click Here</a>{{ ' to restock inventory.' }}
                    </p>
                    @else

                    <div class="row">

                            <div class="col-md-2" style="text-align: center;">
                                {{ Form::open([
                                'method' => 'GET',
                                'route' => ['items.create']
                                ])
                                }}
                                {{ Form::submit('Add New Item') }}
                                {{ Form::close() }}
                            </div>
    
                        </div>

                    <hr>

                    @foreach ($item as $item)

                    <div class="container">

                        <div class="row">
                            <div class="col-md-4">
                                <a href="#">Entry #:</a> <br>
                                <a href="#">Name:</a> <br>
                                <a href="#">Type:</a> <br>
                                <a href="#">Quantity:</a> <br>
                                <a href="#">Description:</a><br><br>

                                <div>
                                    <small id="actionBlock" class="form-text text-muted">

                                        <div class="row">

                                            <div class="col-md-2">

                                                {{ Form::open([
                                                'method' => 'GET',
                                                'route' => ['items.edit', $item->id]
                                                ])
                                                }}
                                                {{ Form::submit('Edit') }}
                                                {{ Form::close() }}

                                            </div>

                                            <div class="col-md-2">

                                                {{ Form::open([
                                                'method' => 'DELETE',
                                                'route' => ['items.destroy', $item->id]
                                                ])
                                                }}
                                                {{ Form::submit('Delete') }}
                                                {{ Form::close() }}

                                            </div>

                                        </div>

                                    </small>

                                </div>

                            </div>
                            <div class="col-md-4">
                                {{ $item->id }} <br>
                                {{ $item->name }} <br>
                                {{ $item->type }} <br>
                                {{ $item->quantity }} <br>
                                {{ $item->description }} <br><br>

                            </div>
                        </div>

                        <hr>
                    </div>

                    @endforeach

                    <div class="row">

                        <div class="col-md-2">
                            {{ Form::open([
                            'method' => 'GET',
                            'route' => ['items.create']
                            ])
                            }}
                            {{ Form::submit('Add New Item') }}
                            {{ Form::close() }}
                        </div>

                    </div>

                    @endif

                </div>
            </div>
        </div>
    </div>

</div>

@endsection

demo-store/resources/views/items/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        
    @if(session('successCreate'))
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="alert alert-success">
                        {{ session('successCreate') }}
                    </div>
                </div>
            </div>
    @elseif(session('successUpdate'))
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="alert alert-success">
                        {{ session('successUpdate') }}
                    </div>
                </div>
            </div>
    @endif
    
    @if (session('status'))
        <div class="card-body">
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
        </div>
    @endif
        
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Item Properties </div>

                <div class="card-body">

                    <div class="container">

                        <div class="row">
                            <div class="col-md-4">
                                <a href="#">ID#:</a> <br>
                                <a href="#">Name:</a> <br>
                                <a href="#">Type:</a> <br>
                                <a href="#">Quantity:</a> <br>
                                <a href="#">Description:</a><br><br>
                            </div>
                            <div class="col-md-4">
                                @foreach ($item as $item)
                                {{ $item->id }} <br>
                                {{ $item->name }} <br>
                                {{ $item->type }} <br>
                                {{ $item->quantity }} <br>
                                {{ $item->description }} <br><br>
                                @endforeach
                            </div>
                        </div>

                    </div>

                </div>
            </div>

            <div class="card">
                <div class="card-header">

                    <small id="actionBlock" class="form-text text-muted">


                        <div class="row">
                            <div class="col-md-2">
                                {{ Form::open([
                                'method' => 'GET',
                                'route' => ['items.index']
                                ])
                                }}
                                {{ Form::submit('View All Items') }}
                                {{ Form::close() }}
                            </div>
                            <div class="col-md-2">
                                {{ Form::open([
                                'method' => 'GET',
                                'route' => ['items.create']
                                ])
                                }}
                                {{ Form::submit('Add New Item') }}
                                {{ Form::close() }}
                            </div>

                            <div class="col-md-2">
                                {{ Form::open([
                                'method' => 'GET',
                                'route' => ['items.edit', $item->id]
                                ])
                                }}
                                {{ Form::submit('Edit This Item') }}
                                {{ Form::close() }}
                            </div>


                            <div class="col-md-2">
                                {{ Form::open([
                                'method' => 'DELETE',
                                'route' => ['items.destroy', $item->id]
                                ])
                                }}
                                {{ Form::submit('Delete') }}
                                {{ Form::close() }}
                            </div>
                        </div>

                    </small>



                </div>
            </div>
        </div>
    </div>

</div>

@endsection